
<?php
/*------------------------------------------------------------------------
 # VT Products - Version 1.0
 * Copyright (C) 2013 The VT Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: VT Theme
 * Websites: http://www.vttheme.com
-------------------------------------------------------------------------*/
$categoryList = $this->getListCategoriesFilter();
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$uniqued = rand().time();

$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;

if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}
$datefnsp = $this->getLimitationTimeFinish();
$to_date = new DateTime($datefnsp); 
?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<?php if($this->title!="") : ?>
<div class="tab-item">
	<ul>
		<li class="active"><a href="#">
			<?php echo $this->title; ?>
		</a></li>
		<li class="countdown-upgrade"><span class="title"><?php echo "ENDS IN";?></span><div class="defaultCountdown"></div></li>
	</ul>
</div>
<?php endif; ?>
<div id="vt_slider<?php echo $uniqued; ?>" class="block vt-slider">
	<div class="slider-inner">
    	<div class="block-title-slider">

    		<?php /* if($this->title!="") : ?>
    			<h3><?php echo $this->title;?></h3>
			<?php endif; */ ?>
    		<?php if($this->pretext!="") : ?>
    			<p class="pretext"><?php echo $this->pretext;?></p>
			<?php endif; ?>					
    	</div>
	    <div class="container-slider">
		    <div class="products-grid">
		    <?php 
		    	$i=0;
		    	foreach($_productCollection as $_product) : ?>
		        <?php
		        $i++;
		        $now = date("Y-m-d H:m:s");
		        $newsFrom= $_product->getNewsFromDate();
		        $newsTo=  $_product->getNewsToDate();
		        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
		        $special_from_date = $_product->getSpecialFromDate();
		        $special_to_date = $_product->getSpecialToDate();    
				
				//print_r($to_date);
		        ?>
		        <div class="item">
		        	<?php   						
		                if($newsFrom != ''){                            
		                if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }else{
		                if(($newsTo != "") && $newsTo >= $now){ 
		                ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }?>
		                <?php 
		                if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
		                    <div class='sale-item'>
		                        <span class='first'><?php
		                        $saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
		                        <?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
		                    </div>
		             <?php } ?>  
					<div class="item-wrap">
                    <div class="item-image">   
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth,$imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                        </a>
                        <div class="item-btn">
                        	<div class="box-inner">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                               <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>                            
                           <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
							<span class="qview"><a href="<?php echo $_product->getProductUrl() ?>" ></a></span>
                        	</div>                            
                        </div>  
                        <?php if($_product->isSaleable()): ?>
                            <a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
                        <?php endif; ?>
						
                    </div>   
                       
                    <div class="pro-info">
                        <div class="pro-inner">                        	
                           <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
                           <div class="pro-content">    
                                <div class="wrap-price"> 
                                <?php echo $this->getPriceHtml($_product, true) ?> 
                                </div>
                                 <?php echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
                           </div>
                        </div>                                                                        
                    </div>
                    
                </div><!--end item wrap -->
		        
				</div>
		    <?php endforeach; ?>
		    </div>
		</div>
		<div class="navslider">
			<a class="prev" href="#">Prev</a>
			<a class="next" href="#">Next</a>
		</div>
	</div>
</div>
<?php if($special_to_date != ''){ ?>
<script>
	jQuery(document).ready(function($){
		var y = <?php echo $to_date->format('Y'); ?>;
		var m = <?php echo ($to_date->format('m')-1); ?> ;
		var d = <?php echo $to_date->format('d'); ?>;
		var h = <?php echo $to_date->format('H'); ?>;
		var mi =<?php echo $to_date->format('i'); ?>;
		var s = <?php echo $to_date->format('s'); ?>;
		$('.defaultCountdown').countdown({    	
			until: new Date(y, m, d, h, mi, s),
			labels: ['YEA', 'MON', 'WEE', 'DAY', 'HOU', 'MIN','SEC'],
			labels1: ['YEA', 'MON', 'WEE', 'DAY', 'HOU', 'MIN', 'SEC'],     
			alwaysExpire: false,
			onExpiry: function(){

			},						
			serverSync: 'Aug 13, 2014 08:39:29 +0000'
		});
	});
</script> 
<?php }?>
<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        $('#vt_slider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
        	items: 4,
            itemsCustom: [ 
            	[0, <?php echo $this->screen_phone; ?>], 
            	[480, <?php echo $this->screen_xs; ?>], 
            	[768, <?php echo $this->screen_sm; ?>], 
            	[992, <?php echo $this->screen_md; ?>], 
            	[1200, <?php echo $this->screen_lg; ?>] 
            ],
            pagination: false,
            slideSpeed : 800,
            addClassActive: true,
            scrollPerPage: false,
            touchDrag: false,
			afterAction: function (e) {
			    if(this.$owlItems.length > this.options.items){
			        $('#vt_slider<?php echo $uniqued; ?> .navslider').show();
			    }else{
			        $('#vt_slider<?php echo $uniqued; ?> .navslider').hide();
			    }
			}
            //scrollPerPage: true,
        });
		$('#vt_slider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
			e.preventDefault();
			$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
		});
		$('#vt_slider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
			e.preventDefault();
			$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
		});
    });
//]]>
</script>
<?php endif; ?>