<?php
$_productCollection = $this->_getProductCollection();
$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
?>
<?php if($_productCollection->count()){ ?>
<div class="slider-inner">
    <div class="container-slider">
         <div class="products-grid">
        <?php foreach($_productCollection as $_product) : 
        	
        ?>
            <?php
            $now = date("Y-m-d H:m:s");
            $newsFrom= $_product->getNewsFromDate();
            $newsTo=  $_product->getNewsToDate();
            $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
            $special_from_date = $_product->getSpecialFromDate();
            $special_to_date = $_product->getSpecialToDate();    
            ?>
            <div class="item">
            	<?php   
                    if($newsFrom != ''){                            
                    if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
                        <div class='new-item'><?php echo $this->__("new"); ?></div>
                    <?php }
                    }else{
                    if(($newsTo != "") && $newsTo >= $now){ 
                    ?>
                        <div class='new-item'><?php echo $this->__("new"); ?></div>
                    <?php }
                    }?>
                    <?php 
                    if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
                        <div class='sale-item'>
                            <span class='first'><?php
                            $saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
                            <?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
                        </div>
                 <?php } ?>  
        		<div class="item-wrap">
                <div class="item-image">   
                    <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                    <img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth,$imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                    </a>
                    <div class="item-btn">
                    	<div class="box-inner">
                        <?php if ($this->helper('wishlist')->isAllow()) : ?>
                           <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
                        <?php endif; ?>                            
                       <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                        <a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
                        <?php endif; ?>
						<span class="qview"><a href="<?php echo $_product->getProductUrl() ?>" ></a></span>
                    	</div>                            
                    </div>  
                    <?php if($_product->isSaleable()): ?>
                        <a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></a>
                    <?php else: ?>
                        <a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
                    <?php endif; ?>
                </div>   
                   
                <div class="pro-info">
                    <div class="pro-inner">
                       <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
                       <div class="pro-content">    
                            <div class="wrap-price"> 
                            <?php echo $this->getPriceHtml($_product, true) ?> 
                            </div>
                             <?php echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
                       </div>
                    </div>                                                                        
                </div>
                
            </div><!--end item wrap -->
            </div>
        <?php endforeach; ?>
        </div>
    </div>
    <div class="navslider">
        <a class="prev" href="#">Prev</a>
        <a class="next" href="#">Next</a>
    </div>
</div>
<?php }else{ 
   echo $this->__('Has no item to show!');
}
?>