<div class="header-container header-style-4">
	<div class="header-top">
		<div class="container">
			<div class="row">
				<div class="col-lg-5 col-md-5 col-sm-5 language-currency-top">
					<?php echo $block->getChildHtml('currency-header'); ?>
					<?php echo $block->getChildHtml('language-header'); ?>
					
				</div>
				
				<div class="col-lg-7 col-md-7 col-sm-7 toplinks-header">
					 <ul class="links-account">
						<li class="account-link hidden-xs">
							<a href="<?php echo $block->getUrl('customer/account')?>" title="<?php echo __('My Account');?>" ><?php echo __('My Account');?></a>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('account-dropdown')->toHtml();?>
						</li>

						<li class="register-link-help hidden-xs">
							<a href="#" title="<?php echo __('Help');?>" ><?php echo __('Help');?></a>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('help-dropdown')->toHtml();?>
						</li>
						<li class="checkout hidden-xs"><a href="<?php echo $block->getUrl('checkout')?>" title="<?php echo __('Checkout');?>" ><?php echo __('Checkout');?></a></li>
						<?php 
							$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
							$customerSession = $objectManager->get('Magento\Customer\Model\Session');
							if($customerSession->isLoggedIn()) { 
							?>
							<li><a class="popup-logout" href="<?php echo $block->getUrl('customer/account/logout')?>" title="<?php echo __('Logout');?>"><?php echo __('Logout');?></a></li>
							<?php }else {
							 ?>
							<li><a class="popup-login" data-toggle="modal" data-target="#modal-login" href="<?php echo $block->getUrl('customer/account/login/')?>" title="<?php echo __('Login')?>"><?php echo __('Login')?></a></li>	
							<li><a class="popup-login" href="<?php echo $block->getUrl('customer/account/create/')?>" title="<?php echo __('Register')?>"><?php echo __('Register')?></a></li>

							<?php }	?>
					</ul>
					
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-middle">
		<div class="container">
			<div class="row">
				<div class="col-lg-3 col-sm-3 logo-header">
					<?php echo $block->getChildHtml('logo-header'); ?>
				</div>
				
				<div class="col-lg-9 col-sm-9 header-middle-right">
					<div class="middle-right-content">
						<div class="minicart-header">
							<div class="minicart-content">
								<?php echo $block->getChildHtml('cart-header'); ?>
							</div>
							<ul class="wishlist-compare hidden-xs hidden-sm">
							<?php echo $block->getLayout()->createBlock('Magento\Framework\View\Element\Template')->setTemplate('Magento_Wishlist::link.phtml')->toHtml(); ?>
							  <?php echo $block->getChildHtml('compare-header-link'); ?>

							</ul>
							<?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-contact-header')->toHtml(); ?>
						</div>
													
						
						
						
					</div>
				</div>
			</div>
		</div>
	</div>
	
	<div class="header-bottom">
		<div class="container">
			<div class="main-megamenu">
				<div class="row">
					<div class="col-md-3 col-sm-4">
							<div class="yt-menu">
									<div class="menu-under">					
										<div class="navigation-container <?php ($_config->getGeneral('menu_style') == 'megamenu') ? "":" css-menu-wrap"; ?>">
											<?php
												if($_config->getGeneral('menu_style') == 'megamenu'){ ?>
												 <div id="btn_vert" class="btn-ver-menu" title="<?php echo __('ALL CATEGORIES');?>">
														<div class="txt-btn g2font"><?php echo __('ALL CATEGORIES');?></div>
												 <?php echo $block->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('block-menu-vetical')->toHtml(); ?>
												 </div>
												<?php } else {
													echo $block->getChildHtml('navigation-header');
												}
											?>
											<div class="navigation-mobile-container">
												<?php echo $block->getChildHtml('navigation.mobile'); ?>
											</div>
										</div>
									</div>
								</div>
							
					</div>		
				 	<div class="col-md-9 col-sm-8 searchbox">
						<div class="searchbox-header">
								<?php echo $block->getChildHtml('search-header-pro'); ?>
						</div>
							
					</div>			
				</div>
			</div>	
		</div>
	</div>
</div>
<script>

						jQuery(document).ready(function($){
							$( "#btn_vert" ).click(function() {
								$('.sm_megamenu_wrapper_vertical_menu').slideToggle(200);
								$(this).toggleClass('active');
							});
						});
					
</script>

