<?php
/*------------------------------------------------------------------------
# SM Basic Products - Version 2.1.0
# Copyright (c) 2015 YouTech Company. All Rights Reserved.
# @license - Copyrighted Commercial Software
# Author: YouTech Company
# Websites: http://www.magentech.com
-------------------------------------------------------------------------*/

use Magento\Framework\App\Action\Action;
$list = $block->_getSelectSource();
$helper = $this->_helper();
	
if (!empty($list)) { 
	$uniqued = 'sm_basic_products_' . time() . rand();
	$class_respl = 'bs-resp01-' . $this->_getConfig('nb_column1', 3) . ' bs-resp02-' . $this->_getConfig('nb_column2', 3) . ' bs-resp03-' . $this->_getConfig('nb_column3', 3) . ' bs-resp04-' . $this->_getConfig('nb_column4', 2) . ' bs-resp05-' . $this->_getConfig('nb_column5', 1);
?>

    <?php if ($this->_getConfig('pretext') != null) { ?>
		<div class="bs-pretext">
			<?php echo $this->_getConfig('pretext'); ?>
		</div>
	<?php } ?>

 <div class="sm-basic-products block">	
 	<div class="block-title">
		<strong><?php echo $this->_getConfig('title', 'Sm Basic Products'); ?></strong>
	</div>
    <div class="products-grid">
        <!-- Begin bs-items     -->
        <div class="product-slider block-content-products">
            <?php $j = 0; foreach ($list as $_product) { $j++;?>
                <!-- Begin bs-item-cf -->
                <div class="item bs-item cf">
                    <!-- Begin bs-item-inner -->
                    <div class="item-inner">
                        <?php if ($_product->_image) { ?>
                            <div class="box-image">
                                <a href="<?php echo $_product->link ?>"
                                   title="<?php echo $_product->title; ?>"
                                    <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                    >
                                    <img src="<?php echo $_product->_image; ?>"
                                         title="<?php echo $_product->title; ?>"
                                         alt="<?php echo $_product->title; ?>"
                                        >
                                </a>
                            </div>
                        <?php }?>

                        <!-- Begin bs-content -->
                        <?php  ?>
						<div class="box-info">

                            <?php if ((int)$this->_getConfig('product_title_display', 1)) { ?>
                                <h2 class="product name product-item-name product-name">
                                    <a href="<?php echo $_product->link; ?>" title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $helper->truncate($_product->title, $this->_getConfig('product_title_maxlength')); ?>
                                    </a>
                                </h2>
                            <?php } ?>
							
							<?php if ($this->_getConfig('product_source') != 'media') { ?>
							
								<?php if ((int)$this->_getConfig('product_reviews_count', 1)) {
										$templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
										echo $block->getReviewsSummaryHtml($_product,$templateType,true); 
								} ?>

                                <?php if ((int)$this->_getConfig('product_price_display', 1)) {
									echo $this->getProductPrice($_product);
                                } ?>
								
							<?php } ?>
							
                            <?php if ((int)$this->_getConfig('product_description_display', 1) && $helper->_trimEncode($_product->_description) != '') { ?>
                                <div class="bs-description">
                                    <?php echo $_product->_description; ?>
                                </div>
                            <?php } ?>
							
                            <?php if ($this->_getConfig('cat_title_display') == 1 && $this->_getConfig('product_source') != 'media') { ?>
                               <div class="bs-category"><?php echo __('Category:&nbsp') ;?>
									<a  href="<?php echo $_product->cat_link; ?>"  title="<?php echo $_product->cat_title; ?>"  <?php echo $helper->parseTarget($this->_getConfig('target')); ?>>
										 <?php echo  $helper->truncate($_product->cat_title, $this->_getConfig('category_title_max_characs', 25)); ?>
									</a>
									
                                </div>
                            <?php } ?>

								
                            <?php if ($this->_getConfig('product_source') != 'media') { ?>

								<?php if ((int)$this->_getConfig('product_addcart_display', 1) ||(int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
								<div class="product actions product-item-actions">
									

									
								</div>
								<?php } ?>
                            <?php } ?>

                            <?php if ($this->_getConfig('product_readmore_display') == 1) { ?>
                                <div class="bs-detail">
                                    <a href="<?php echo $_product->link ?>"
                                       title="<?php echo $_product->title; ?>"
                                        <?php echo $helper->parseTarget($this->_getConfig('target')); ?>
                                        >
                                        <?php echo $this->_getConfig('product_readmore_text', 'Details'); ?>
                                    </a>
                                </div>
                            <?php } ?>
							
							<?php if ($this->_getConfig('product_source') != 'media') { ?>
								<?php if ((int)$this->_getConfig('product_addcart_display', 1) ||(int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
								<div class="bottom-action">
									<?php /*if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
									<?php if ($_product->isSaleable()){ ?>
											<?php if ($_product->getTypeInstance()->hasRequiredOptions($_product)){ ?>
												<button class="action tocart primary btn-action btn-cart" data-mage-init='{"redirectUrl": {"url": "<?php echo $block->getAddToCartUrl($_product) ?>"}}' type="button" title="<?php  echo __('Add to Cart') ?>">
													<span><?php  echo __('Add to Cart') ?></span>
												</button>
											<?php } else { ?>
												<?php $postDataHelper = $this->helper('Magento\Framework\Data\Helper\PostHelper');
												$postData = $postDataHelper->getPostData($block->getAddToCartUrl($_product), ['product' => $_product->getEntityId()])
												?>
												<button class="action tocart primary btn-action btn-cart"
														data-post='<?php echo $postData; ?>'
														type="button" title="<?php  echo __('Add to Cart') ?>">
													<span><?php echo __('Add to Cart') ?></span>
												</button>
											<?php } ?>
										<?php } else { ?>
											<?php if ($_product->getIsSalable()){ ?>
												<div class="stock available"><span><?php  echo __('In stock') ?></span></div>
											<?php } else { ?>
												<div class="stock unavailable"><span><?php  echo __('Out of stock') ?></span></div>
											<?php } ?>
										<?php } ?>
									<?php } */?>
									
									
							<?php if ((int)$this->_getConfig('product_addcart_display', 1)) { ?>
							<div class="actions-primary">
								 <?php if ($_product->isSaleable()): ?>
									<?php $postParams = $this->getAddToCartPostParams($_product); 
									$objectManager =  \Magento\Framework\App\ObjectManager::getInstance();
									$session = $objectManager->get('\Magento\Framework\View\Element\FormKey');
									?>
									<form data-role="tocart-form" action="<?php /* @escapeNotVerified */ echo $postParams['action']; ?>" method="post">
										<input type="hidden" name="product" value="<?php /* @escapeNotVerified */ echo $postParams['data']['product']; ?>">
										<input type="hidden" name="<?php /* @escapeNotVerified */ echo Action::PARAM_NAME_URL_ENCODED; ?>" value="<?php /* @escapeNotVerified */ echo $postParams['data'][Action::PARAM_NAME_URL_ENCODED]; ?>">
										<?php echo $block->getBlockHtml('formkey')?>
										<input  name="form_key" type="hidden" value="<?php echo $session->getFormKey(); ?>" />
										<button type="submit"
												title="<?php echo $block->escapeHtml(__('Add to Cart')); ?>"
												class="action tocart btn-action btn-cart">
											<span><?php /* @escapeNotVerified */ echo __('Add to Cart') ?></span>
										</button>
									</form>
								<?php else: ?>
									<?php if ($_product->getIsSalable()): ?>
										<div class="stock available"><span><?php /* @escapeNotVerified */ echo __('In stock') ?></span></div>
									<?php else: ?>
										<div class="stock unavailable"><span><?php /* @escapeNotVerified */ echo __('Out of stock') ?></span></div>
									<?php endif; ?>
								<?php endif; ?>
							</div>
							<?php } ?>									
									
									

									<?php if ((int)$this->_getConfig('product_addwishlist_display', 1) || (int)$this->_getConfig('product_addcompare_display', 1)) { ?>
										
											<?php if ($this->helper('Magento\Wishlist\Helper\Data')->isAllow() && (int)$this->_getConfig('product_addwishlist_display', 1) ){ ?>
												<a href="#" class="action towishlist btn-action link-wishlist" title="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>"  aria-label="<?php echo $block->escapeHtml(__('Add to Wish List')); ?>" data-post='<?php /* @escapeNotVerified */ echo $block->getAddToWishlistParams($_product); ?>' data-action="add-to-wishlist"  role="button">
													<span><?php /* @escapeNotVerified */ echo __('Add to Wish List') ?></span>
												</a>
											<?php } ?>
											<?php if ($block->getAddToCompareUrl() &&  (int)$this->_getConfig('product_addcompare_display', 1)){ ?>
												<?php
												$compareHelper = $this->helper('Magento\Catalog\Helper\Product\Compare');
												?>
												<a href="#"  class="action tocompare btn-action link-compare"  title="<?php echo $block->escapeHtml(__('Add to Compare')); ?>" aria-label="<?php echo $block->escapeHtml(__('Add to Compare')); ?>"  data-post='<?php /* @escapeNotVerified */ echo $compareHelper->getPostDataParams($_product); ?>' role="button">
												<span><?php /* @escapeNotVerified */ echo __('Add to Compare') ?></span>
											</a>
									<?php }; ?>
										
									<?php } ?>
								</div>
								<?php } ?>
                            <?php } ?>
                        </div>
						
                        <!-- End bs-content -->
                    </div>
                    <!-- End bs-item-inner -->
                </div><!-- End bs-item-cf -->
			
            <?php } ?>
        </div>
		 </div>
		<script type="text/javascript">
				// <![CDATA[
								jQuery(document).ready(function($) {
									var product_slider = $(".product-slider");
									product_slider.owlCarousel({				
										nav: true,
										dots:false,
										margin: 30,
										
										responsive: {
											0: {
												items:<?php echo $this->_getConfig('nb_column5', 1);?>
											},
											480: {
												items:<?php echo $this->_getConfig('nb_column4', 2);?>
											},
											768: {
												items:<?php echo $this->_getConfig('nb_column3', 3);?>
											},
											991: {
												items:<?php echo $this->_getConfig('nb_column2', 3);?>
											},						
											1200: {
												items:<?php echo $this->_getConfig('nb_column1', 3);?>
											}
										}
									});	  
								});
				// ]]>
		</script>
        <!-- End bs-items -->
    </div><!-- End Sm-basic-products -->
   <?php if ($this->_getConfig('posttext') != null) { ?>
		<div class="bs-posttext">
			<?php echo $this->_getConfig('posttext'); ?>
		</div>
	<?php } ?>
<?php
} else {
	echo '<h1 style="color:#f1703d;">Has no content to show!</h1>';
}
?>