<?php
/*------------------------------------------------------------------------
 # Copyright (c) 2014 VnThemePro Company. All Rights Reserved.
 # @license - Copyrighted Commercial Software
 # Author: VnThemePro Company
 # Websites: http://www.vnthemepro.com
-------------------------------------------------------------------------*/?>

<a id="vt-totop" href="#" title="Go to Top"></a>
<script type="text/javascript">
	jQuery(document).ready(function($){  
		$("#vt-totop").hide();
		$(function () {
			var wh = $(window).height();
			var whtml =  $(document).height();
			$(window).scroll(function () {
				if ($(this).scrollTop() > whtml/10) {
					$('#vt-totop').fadeIn();
				} else {
					$('#vt-totop').fadeOut();
				}
			});
			$('#vt-totop').click(function () {
				$('body,html').animate({
					scrollTop: 0
				}, 800);
				return false;
			});
		});
	});
</script>