<?php
	$_config = $this->helper('Sm\Lovefashion\Helper\Data');
	$baseUrl = $_config->getUrl();
	$store_id = $_config->getStoreId();

	$theme_color = $_config->getGeneral('theme_color');
	$header_select  = $_config->getThemeLayout('header_style');
	$footer_select  = $_config->getThemeLayout('footer_style');
	$home_select  = $_config->getThemeLayout('home_style');
	$detail_select  = $_config->getProductDetail('detail_style');

	$body_font_size = $_config->getGeneral('font_size');
	$text_color = $_config->getGeneral('body_text_color');
	$link_color = $_config->getGeneral('body_link_color');
	$link_hover_color = $_config->getGeneral('body_link_hover_color');
	$body_background_color = $_config->getGeneral('body_background_color');

	$main_font = $_config->getGeneral('body_font');
	$main_google_font = $_config->getGeneral('body_google_font');
	$google_font_element = $_config->getGeneral('google_font_targets');
	$element_google_font_name = $_config->getGeneral('element_google_font');

	/* BACKGROUND IMAGE */
	$background_path = "";
	$use_bg_image = $_config->getGeneral('use_background_image');
	$use_custom_image = $_config->getGeneral('use_customize_image');

	$background_repeat = $_config->getGeneral('background_repeat');
	$background_position = $_config->getGeneral('background_position');

	if($use_bg_image && $use_custom_image == '0'){
		$bg_pattern = $_config->getGeneral('body_background_image');
		$background_path = $baseUrl.'pub/media/pattern/'.$bg_pattern.'.png';
	}

	if($use_bg_image && $use_custom_image == '1'){
		$custom_bg = $_config->getGeneral('background_customize_image');
		$background_path = $baseUrl.'pub/media/pattern/'.$custom_bg;
	}
	/* END BACKGROUND IMAGE */

	if($main_font != 'google_font'){
		$body_font_family = $main_font;
	} else {
		$namefontmain = explode(":",str_replace("+", " ", $main_google_font)); 
		$body_font_family = $namefontmain[0];
	}

	//google font element
	$namegooglefont_element = explode(":",str_replace("+", " ", $element_google_font_name));
	$element_googlefont = $namegooglefont_element[0];
	//end google font element

	require_once ("vendor/oyejorge/less.php/lessc.inc.php");
	$less = new lessc;

	$less->setVariables(array(
		"@theme_color" => '#'.$theme_color,
		"@body_font_size" => $body_font_size,
		"@body_font_family" => $body_font_family,
		"@text_color" => '#'.$text_color,
		"@link_color" => '#'.$link_color,
		"@link_hover_color" => '#'.$link_hover_color,
		"@body_background_color" => '#'.$body_background_color,
		"@background_path" => '"'.$background_path.'"',
		"@background_repeat" => $background_repeat,
		"@background_position" => $background_position
	));
	
	require_once ("config_less.phtml"); /* define variable: $str_less*/
	
	$mixin            = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/_mixin.less');
	$header_style     = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/header/'.$header_select.'/_styles.less');
	$header_style_res = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/header/'.$header_select.'/_responsive.less');
	$footer_style     = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/footer/'.$footer_select.'/_styles.less');
	$footer_style_res = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/footer/'.$footer_select.'/_responsive.less');
	$home_style       = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/home/'.$home_select.'/_styles.less');
	$home_style_res   = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/home/'.$home_select.'/_responsive.less');
	$detail_style     = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/detail/'.$detail_select.'/_styles.less');
	$detail_style_res = file_get_contents('app/design/frontend/Sm/lovefashion/web/css/detail/'.$detail_select.'/_responsive.less');

	$style = str_replace('"', "'", $mixin.$header_style.$header_style_res.$footer_style.$footer_style_res.$home_style.$home_style_res.$detail_style.$detail_style_res); 	
	$extend_css = $less->compile($style);
	$out = $less->compile($str_less).$extend_css; 

	file_put_contents( "pub/static/frontend/Sm/lovefashion/en_US/css/config_".$store_id.".css", $out );


	$array_files = array(
		"app/design/frontend/Sm/lovefashion/web/css/yttheme.less"=>"pub/static/frontend/Sm/lovefashion/en_US/css/yttheme.css"
	);
	foreach($array_files as $key=>$val)
	{
		$less->compileFile($key, $val);
	}
	
?>