<?php
$str_less = "
		body{
		  background-color: @body_background_color;
		  font-family: @body_font_family;
		  font-size: @body_font_size;
		  color: @text_color;
		  line-height: 1.66;
			background-image:url('@{background_path}');
			background-repeat: @background_repeat;
			background-position: @background_position;
		}

		.label{
		  color: @text_color;
		}

		a,
		a:focus,
		a:visited{
		  color: @link_color;
		}

		a:hover{
		  color: @theme_color;
		}

		/* GENERAL */
		.owl-controls .owl-nav div:hover,
		.page-title:before,
		button:hover,
		.cart-container .action.continue:hover,
		a.action.primary:hover,
		.sambar-inner:before{
		  background-color: @theme_color;
		}

		

		.cart-container .cart-summary .coupon .actions-toolbar .primary .apply.primary:hover,
		.modal-footer .action-primary.action-accept:hover,
		.slider-ourmember .owl-dots .owl-dot:hover,
		.slider-ourmember .owl-dots .owl-dot.active,
		.navigation-wrapper .navigation > ul > li:hover > a,.navigation-wrapper .navigation > ul > li.has-active > a,
		.navigation-wrapper .navigation > ul:before,
		.control-qty .quantity-controls:hover{
		  background-color: @theme_color;
		}
		.navigation-wrapper .navigation > ul > li li.active > a , .navigation-wrapper .navigation > ul > li li.has-active > a ,
		.navigation-wrapper .navigation > ul > li li.parent:hover > a {color: @theme_color;}
		.block-minicart .minicart-items .product-item-details .product-item-name a:hover{
		  color: @theme_color;
		}
		.header-style-3{
			.navigation-wrapper .navigation > ul > li:hover > a ,.navigation-wrapper .navigation > ul > li:first-child > a  {
			background-color:@link_hover_color;
			}
		}
		.cms-index-index .header-style-3 .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li:first-child  > a {
			background-color:@link_hover_color;
		}
		.header-style-4 .btn-ver-menu:before , .header-style-4 .ct-list li:hover fa  {color: @theme_color;}
		.header-style-4 .btn-ver-menu:hover {background-color: @theme_color;}

		#yt-totop:hover { background-color: @theme_color !important;}


		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--right:hover,
		.fotorama__nav-wrap--horizontal .fotorama__thumb__arr--left:hover{
		  background-color: @theme_color;
		  border-color: @theme_color;
		}

		.fotorama-item .fotorama__nav--thumbs .fotorama__nav__frame.fotorama__active,.owl-controls .owl-nav div:hover{
		  border-color: @theme_color;
		}

		.more-w .more-view:hover{
		  color: @theme_color;
		}

		.breadcrumbs .items .item:hover{
		  border-color: @theme_color;

		  &:before,
		  &:after{
			border-color: @theme_color;
		  }
		}
		.newletter-home .bg-newletter .form.subscribe .actions button:hover {background-color: @theme_color;}
		.lSAction > a {
		  &:hover{
			border-color: @theme_color;
			background-color: @theme_color;
		  }
		}
		/* END GENERAL */

		/* LISTING */
		.sm_quickview_handler:hover ,  .tocart.btn-cart:hover, .item .item-inner  .bottom-action .btn-action:hover {
			background-color: @theme_color !important;
		}
		.block{
		  .block-title{
			&:before{
			  background-color: @theme_color;
			}
		  }
		  .owl-controls .owl-nav div:hover{
			background-color: @theme_color;
		  }
		  .owl-controls .owl-nav div:hover{
			border-color: @theme_color;
			}
		}

		.quick-info .inner:after{
			border-color: transparent @link_hover_color transparent transparent !important;
		}

		
		.price-box .price { color: @theme_color;}
		.products-grid {
		  .item {
			.item-inner {
			  .box-info {
				.bottom-action{
				  .btn-action.btn-cart{

					&:hover{
					  background-color: @theme_color;
					  border-color: @theme_color!important;
					}
				  }

				  .btn-action{
					&.link-wishlist{
					  &:hover{
						&:before{
						  color: @theme_color;
						}
					  }
					}

					&.link-compare{
					  &:hover{
						&:before{
						  color: @theme_color;
						}
					  }
					}

					&:hover{
					  border-color: @theme_color!important;
					}
				  }
				}
			  }
			}
		  }
		}

		.products-list {
		  .item {
			.item-inner {
			  .box-info-list {
				.bottom-action{
				  form{
					.btn-action{
					  &:hover{
						background-color: @theme_color;
						border-color: @theme_color!important;
					  }
					}
				  }


				  .btn-action{
					&.link-wishlist,
					&.link-compare{
					  &:hover{
					  	border-color: @theme_color!important;

					  	&:before{
					  		color: @theme_color!important;
							border-color: @theme_color!important;
					  	}

					  }
					}
				  }
				}
			  }
			}
		  }
		}

		.toolbar{
		  .modes{
			.modes-mode{
			  &.mode-grid{
				&:hover:before,
				&.active:before{
				  color: @theme_color;
				}
			  }

			  &.mode-list{
				&:hover:before,
				&.active:before{
				  color: @theme_color;
				}
			  }
			}
		  }


		  .pages{
			.pages-items{
			  .item{
				&:hover{
				  background-color: @theme_color;
				  border-color: @theme_color;
				}

				&.current{
				  background-color: @theme_color;
				  border-color: @theme_color;

				}

			  }
			}
		  }

		}

		.products-sidebar{
		  .item{
			.item-inner{
			  .box-image{
				&:hover{
				  border-color: @theme_color;
				}
			  }
			}
		  }
		}

		/* END LISTING */

		/* DETAIL */
		.info-box-detail .product-info-stock-sku .available span {color: @theme_color;}
		.accordion-style .resp-accordion.resp-tab-active{
			background-color: @theme_color!important;
			border-color: @theme_color!important;
		}


		.detail-title{
		  &:before{
			background-color: @theme_color;
		  }
		}
		.resp-vtabs .resp-tabs-list li:hover,
		.resp-vtabs .resp-tabs-list li.resp-tab-active {
			background-color: @theme_color;	
		}
		.related-wrapper .owl-controls .owl-nav div:hover,
		.upsell-wrapper .owl-controls .owl-nav div:hover
		{
		  color: @theme_color;
		}

		#left-detail .navigation-details .touch-button{
		&.active,&:hover {background-color: @theme_color;}
		}
		.related-wrapper,
		.upsell-wrapper{

		  .owl-controls{
			.owl-nav{
			  div{
				&:hover{
				  border-color: @theme_color!important;
				  background-color: @theme_color!important;
				}
			  }
			}
		  }
		}

		.products-sidebar.block-related .owl-dots .owl-dot{
			&.active, &:hover {background-color: @theme_color;}
		}

		.info-box-detail{

		  .product-options-bottom,
		  .product-add-form{
			.box-tocart{
			  .fieldset{
				.actions{
				  button:hover{
					background-color: @theme_color;
				  }
				}
			  }
			}
		  }

		  .product-social-links{
			.action{
			  &:hover{
				background-color: @theme_color!important;

				
			  }
			}
		  }
		}

		/* horizontal full */


		.product-image-detail{
		  .thumbs-container{
			.thumb-slider{
			  .thumb-item{
				.thumb-image{
					&:hover,
					&.thumb-active{
						border-color:@theme_color;
					}
				}
			  }
			}
		  }
		}
		
		/* end horizontal full */

		/* END DETAIL */

		/* TAB */

		.default-style{
		  .resp-tabs-list{
			li{
			 
			  &.resp-tab-active,&:hover{
				background-color: @theme_color;
				color: #fff;
			  }
			}
		  }
		}

		.vertical-style{
		  .resp-tabs-list li {
			&.resp-tab-active{
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}



		/* END TAB */

		/* HEADER */
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li:hover > a, 
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li.sm_megamenu_actived > a ,
		.sm-searchbox .sm-searchbox-content .actions .btn-searchbox, .cms-index-index  li.home-item-parent > a{
			background-color: @theme_color;
		}
		.header-style-5 .block-cus-hd2 .counter , .header-style-5 .minicart-content .minicart-wrapper .action.showcart .counter.qty {background-color: @theme_color !important; }
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li .sm-megamenu-child .sm_megamenu_actived {
			> a , > a:before {color: @theme_color !important;}
		}
		.wishlist-compare li a:hover ,.wishlist-compare li a:hover:before,
		.sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu .sm_megamenu_head_item .sm_megamenu_title > .sm_megamenu_title a:hover:before,
		ul.my-links > li:hover > a ,ul.my-links > li:hover > a:before, ul.my-links > li .dropdown-link li a:hover
		{color: @theme_color !important;}
		.more-w .more-view{color: @theme_color;}
		.header-style-1{
		  .header-top{
			.header-top-links{
			  .toplinks-wrapper{
				.header.links{
				  li{
					a{
					  &:hover{
						background-color: @theme_color;
					  }
					}
				  }
				}
			  }
			}
		  }

		  .header-middle{
			.middle-right-content{
				.sm-searchbox .sm-searchbox-content .actions .btn-searchbox:hover{
					background-color: @theme_color;
				}
			  .searchbox-header{
				.search-wrapper{
				  .block-content{
					.btn-search-header{
					  &:hover{
						background-color: @theme_color;
					  }
					}
				  }

				}
			  }
			}
		  }
		}

		.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:after {
			  border-color: @theme_color transparent transparent;
		}
		.newletter-home .new-static > h2 span {color: @theme_color;}

		.header-style-2 .header-middle .sm-searchbox .sm-searchbox-content .control .cat-wrapper:hover:before, .header-middle .minicart-wrapper .showcart .counter .counter-number, .block-minicart .block-content > .actions a:hover {
				background-color: @theme_color !important;
		}
		.header-style-3 .header-top , .header-style-3 .header-bottom .minicart-header .minicart-content .cart-wrapper .minicart-wrapper .showcart{background-color: @theme_color !important;}
		.header-style-3 .header-top .language-currency-top, .header-style-3 .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li:hover > a, .header-style-3 .sm_megamenu_wrapper_horizontal_menu .sm_megamenu_menu > li.sm_megamenu_actived > a {
			 background-color: @link_hover_color;
		}
		.block-minicart   .price , .home-item-parent .mega-home-content ul li a:hover:before {
			color: @theme_color !important ;
		}
		.quick-info .inner , .quick-info .inner:before{ background-color: @theme_color;}
		.sm_megamenu_wrapper_vertical_menu .sm_megamenu_menu > li .sm-megamenu-child .sm_megamenu_title.sm_megamenu_actived > a {color: @theme_color;} 
		ul.ct-list li:hover {
			a, i {color: @theme_color !important;}
		}
		/* END HEADER */

		/* HOME */

		.sm-searchbox-popular .sm-searchbox-keyword ul li a:hover{
			color: @link_hover_color;
		}

		.title-home-page:before , .home-page-2 .newlt-left{
		  background-color: @theme_color;
		}
		 
		.sm-categories .cat-wrap .image-cat .btn-categories{
		  background-color: @theme_color;
		}

		
		.sm-listing-tabs .ltabs-items .ltabs-loadmore .ltabs-loadmore-btn{
		  background-color: @theme_color;
		}

		.sm-listing-tabs .owl-controls .owl-nav div:hover{
		  background-color: @theme_color;
		  border-color: @theme_color;
		}

		.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li.tab-sel,
		.sm-listing-tabs .ltabs-tabs-container .ltabs-tabs li:hover{
		  color: @theme_color;
		  border-color: @theme_color;
		}

		.sm_quickview_handler {
		  &:hover{
			background-color: @theme_color;
			border-color: @theme_color;
		  }
		}
		.item-time .deals-countdown , .sm-deals-wrapper .box-image .view-detail:hover {background-color: @theme_color;}
		
		.item-time .deals-countdown:before {border-color: transparent transparent @link_hover_color @link_hover_color !important;}
		.item-time .deals-countdown:after { border-color: transparent @theme_color transparent transparent !important;}
		.collections .collect a:hover,
		.clients-say .block-content-clients-say .owl-controls .owl-nav div:hover{
		  color: @theme_color;
		}

		.top-search{
		  ul{
			li{
			  a{
				&:hover{
				  color: @theme_color;
				}
			  }
			}
		  }
		}


		.collections{
		  .collect{
			a{
			  border-bottom: 2px solid @theme_color!important;

			  &:hover{
				border-top: 1px solid @theme_color!important;
				border-left: 1px solid @theme_color!important;
				border-right: 1px solid @theme_color!important;
			  }
			}
		  }
		}

		.clients-say{
		  .block-content-clients-say{
			.owl-controls{
			  .owl-nav{
				div{
				  &:hover{
					border-color: @theme_color!important;
				  }
				}
			  }
			}
		  }
		}

		.block-subscribe-home{
		  .form.subscribe{
			button.subscribe{
			  background-color: @theme_color;
			}
		  }
		}

		.slider-deal-type2{
		  .products-grid .item .item-inner{
			.box-info{
			  .deals-countdown{
				background-color: @theme_color;
			  }
			}
		  }

		  .owl-controls .owl-nav{
			div{
			  &:hover{
				background: @theme_color;
				border: @theme_color;
			  }
			}
		  }
		}

		/* HOME 1 */
		.clients-say .list-customer .item-cus .cus-image-box:hover{border-color: @theme_color;}
		.clients-say .owl-dots .owl-dot.active, .clients-say .owl-dots .owl-dot:hover {background: @theme_color;}

		.home-page-2 .sm-listing-tabs .title-home-page h2{ border-color: @theme_color;}

		
		/* END HOME */

		/* FOOTER */

		// footer 1

		.footer-container{
		  .footer-bottom{
			.copyright-footer{
			  a{
				color: @theme_color;
			  }
			}
		  }

		  .footer-block{
			.footer-block-content{
			  .links-footer{
				li{
				  a{
					&:hover{
					  color: @theme_color;
					}
				  }
				}
			  }

			  .links-contact{
				li{
				  &:hover{
					&:before{
					  background-color: @theme_color;
					}
				  }
				}
			  }
			}
		  }

		  .categories-footer{
			.footer-links-w{
			  ul{
				li{
				  a:hover{
					color: @theme_color;
				  }
				}
			  }
			}
		  }
		}

		.footer-style-2 .footer-middle .block-subscribe-footer .form.subscribe .action-button button{
			background-color: @theme_color;
		}

		.footer-style-2 .footer-middle .socials-wrap ul li a:hover{
			background-color: @theme_color;
		}

		/* END FOOTER */

		/* LISTING DEALS */
		.sm-listingdeals .listingdeals-items .listingdeals-loadmore .listingdeals-loadmore-btn,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab:hover:before,
		.sm-listingdeals .listingdeals-tabs-container ul .listingdeals-tab.tab-sel:before{
			background-color: @theme_color;
		}
		/* END LISTING DEALS */

		/* LISTING EXTEND */

		.sm-listing-extend .owl-controls .owl-dots .owl-dot:hover,
		.sm-listing-extend .owl-controls .owl-dots .owl-dot.active,
		.sm-listing-extend .owl-controls .owl-nav div:hover{
			border-color: @theme_color;
		}

		/* END LISTING EXTEND */

		/* BONUS */

		.cart-container .cart.main.actions .action,
		.cart-container .cart.table-wrapper .actions-toolbar .action-edit:hover,
		.cart-container .cart.table-wrapper .actions-toolbar .action-delete:hover,
		.cart-container .checkout-methods-items .action.primary.checkout{
		  background-color: @theme_color;
		}
		.about-us .sc-network li a:hover {
			 background-color: @theme_color;
			 border-color: @theme_color;
		}

		/* END BONUS */

		/* PAGE */

		.pricing-title {
		  h2 {
			&:before {
			  background-color: @theme_color;
			}
		  }
		}

		.table-style-1 {
		  .table-container {
			.table-column .table-content .table-detail .button-container a {
			  &:hover{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-2 {
		  .table-container {
			.table-column.column-active .table-content .table-detail .table-header {
			  color: @theme_color;
			}

			.table-column.column-active .table-content .table-detail .table-price .price{
			  color: @theme_color;
			}

			.table-column .table-content .button-container a{
				&:hover,
				&:before{
					background-color: @theme_color!important;
				}
			}

			.table-column.column-active .table-content .button-container a {
			  &:hover,
			  &:before{
				background-color: @theme_color;
			  }
			}
		  }
		}

		.table-style-4 {
		  .table-container {
			.table-column .table-content{
				.table-header,
				.button-container a {
				  background-color: @theme_color;
				}
			}
		  }
		}

		.team-style-2 {
		  .team-container {
			.team-inner .team-info {
			  background-color: @theme_color;
			}
		  }
		}

		.team-style-4 {
		  .team-container {
			.team-inner .team-info .socials li a {
			  background-color: @theme_color;
			}
		  }
		}

		.category-item .image-category .title-category h2 a:hover{
			color:@theme_color!important;
		}

		.accordion-type-1,
		.accordion-type-2,
		.accordion-type-4,
		.accordion-type-5{
			.accordion-heading .panel-title a:hover{
				color: @theme_color;
			}
		}

		.link-list {
		  li {
			a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

			&.category-link-title a {
			  color: @theme_color;
			}
		  }
		}

		.testimonials-style-1 {
		  .testimonials-info {
			.name-client {
			  color: @theme_color;
			}
		  }
		}

		.events-list {
		  .item {
			.event-info {
			  .bottom-info a{
				color: @theme_color;
			  }
			}

			.event-info .event-title h2 a {
			  &:hover{
				color: @link_hover_color;
			  }
			}

		  }
		}

		.w-newsletter {
		  .newsletter-info {
			.form-newsletter-popup .action-newsletter button:hover {
			  background-color: @theme_color;
			}
		  }
		}

		.socials-popup {
		  li {
			a:hover {
			  background-color: @theme_color;
			  border-color: @theme_color;
			}
		  }
		}

		/* END PAGE */

		// RESPONSIVE

		@media (min-width: 1200px) {
		  .header-style-1 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-7 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }

		  .header-style-8 .header-top .header-top-links .toplinks-wrapper .header.links li.myaccount-link a {
			background-color: @theme_color;
		  }
		}

		@media (min-width: 992px) and (max-width: 1199px) {

		}
		@media (max-width: 992px) {
			.header-style-3 .btn-mobile .button-mobile {background-color: @link_hover_color !important;}	
		}

		@media (min-width: 768px) and (max-width: 991px) {
			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}
		}

		@media (max-width: 765px) {
			.main-megamenu .minicart-content .minicart-wrapper .action.showcart .counter.qty .counter-number {
				background-color: @theme_color!important;
			}

			.header-style-1 .header-middle .middle-right-content .sm-searchbox .sm-searchbox-content .actions .btn-searchbox{
				background-color: @theme_color!important;
			}

			.resp-accordion.resp-tab-active{
				background-color:@theme_color;
				border-color:@theme_color;
			}

		}

		@media (max-width: 480px) {

		}
	";
?>