<?php
	$_config = $this->helper('Sm\Lovefashion\Helper\Data');
	$store_id = $_config->getStoreId();
	$config_href = $_config->getUrl() . 'pub/static/frontend/Sm/lovefashion/en_US/css/config_' . $store_id . '.css';
?>

<?php
	$main_font = $_config->getGeneral('body_font');
	$main_google_font = $_config->getGeneral('body_google_font');
	$google_font_element = $_config->getGeneral('google_font_targets');
	$element_google_font_name = $_config->getGeneral('element_google_font');
	$homeStyle = $_config->getThemeLayout('home_style');
?>
<?php if($main_font == 'google_font'){?>
<link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=<?php echo $main_google_font ?>' />
<?php } ?>
<?php if($google_font_element != ''){?>
<link rel='stylesheet' type='text/css' href='//fonts.googleapis.com/css?family=<?php echo $element_google_font_name ?>' />
<?php } ?>
<link  rel="stylesheet" type="text/css"  media="all" href="<?php echo $config_href;?>" />



<!--CUSTOM JS-->
<?php echo $_config->getAdvanced('custom_js');?>

<script>
	jQuery(document).ready(function($){ 
		$('body').addClass("<?php echo $homeStyle . '-style'?>");
	});

</script>

<!--LISTING CONFIG-->
<style>

<?php echo $google_font_element ?>{
	font-family:<?php $namegooglefont_element = explode(":",str_replace("+", " ", $element_google_font_name));
		echo $namegooglefont_element[0];
	?>;
}
	
@media (min-width: 1200px) {
	/* BOXED */	
	<?php if( $_config->getThemeLayout('layout_style')=='boxed' ){?>
		.page-wrapper{
			background-color: #fff;
			max-width: 1200px;
			margin:0 auto;
			overflow-x: inherit;
			box-shadow: 0 0 3px rgba(0,0,0,0.3);
			-webkit-box-shadow: 0 0 3px rgba(0,0,0,0.3);
		}
	<?php } ?>

	/*==1 COLUMN==*/
	<?php
		$one_col_device_1200 = $_config->getProductListing('onecolumn_device_1200');
		$one_class_device_1200 = 100 / $one_col_device_1200 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_1200; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_1200;?>n+1){
		clear:both;
	}
	
	/*==2 COLUMNS==*/
	<?php
		$two_col_device_1200 = $_config->getProductListing('twocolumn_device_1200');
		$two_class_device_1200 = 100 / $two_col_device_1200 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_1200; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_1200;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_1200 = $_config->getProductListing('threecolumn_device_1200');
		$three_class_device_1200 = 100 / $three_col_device_1200 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_1200; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_1200;?>n+1){
		clear:both;
	}
}

@media (min-width: 992px) and (max-width: 1199px) {

	<?php if( $_config->getThemeLayout('layout_style')=='boxed' ){?>
		.page-wrapper{
			background-color: #fff;
			max-width: 970px;
			margin:0 auto;
			box-shadow: 0 0 3px rgba(0,0,0,0.3);
			-webkit-box-shadow: 0 0 3px rgba(0,0,0,0.3);
		}
	<?php } ?>

	/*==1 COLUMN==*/
	<?php
		$one_col_device_992 = $_config->getProductListing('onecolumn_device_992');
		$one_class_device_992 = 100 / $one_col_device_992 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_992; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_992;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
		$two_col_device_992 = $_config->getProductListing('twocolumn_device_992');
		$two_class_device_992 = 100 / $two_col_device_992 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_992; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_992;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_992 = $_config->getProductListing('threecolumn_device_992');
		$three_class_device_992 = 100 / $three_col_device_992 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_992; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_992;?>n+1){
		clear:both;
	}
}

@media (min-width: 768px) and (max-width: 991px) {
	<?php if( $_config->getThemeLayout('layout_style')=='boxed' ){?>
		.page-wrapper{
			background-color: #fff;
			max-width: 750px;
			margin:0 auto;
			box-shadow: 0 0 3px rgba(0,0,0,0.3);
			-webkit-box-shadow: 0 0 3px rgba(0,0,0,0.3);
		}
	<?php } ?>

	/*==1 COLUMN==*/
	<?php
		$one_col_device_768 = $_config->getProductListing('onecolumn_device_768');
		$one_class_device_768 = 100 / $one_col_device_768 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_768; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_768;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
		$two_col_device_768 = $_config->getProductListing('twocolumn_device_768');
		$two_class_device_768 = 100 / $two_col_device_768 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_768; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_768;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
	$three_col_device_768 = $_config->getProductListing('threecolumn_device_768');
	$three_class_device_768 = 100 / $three_col_device_768 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_768; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_768;?>n+1){
		clear:both;
	}
}

@media (min-width: 481px) and (max-width: 767px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_481 = $_config->getProductListing('onecolumn_device_481');
		$one_class_device_481 = 100 / $one_col_device_481 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_481; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_481;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
	$two_col_device_481 = $_config->getProductListing('twocolumn_device_481');
	$two_class_device_481 = 100 / $two_col_device_481 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_481; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_481;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
		$three_col_device_481 = $_config->getProductListing('threecolumn_device_481');
		$three_class_device_481 = 100 / $three_col_device_481 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_481; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_481;?>n+1){
		clear:both;
	}
}

@media (max-width: 480px) {

	/*==1 COLUMN==*/
	<?php
		$one_col_device_less_481 = $_config->getProductListing('onecolumn_device_less_481');
		$one_class_device_less_481 = 100 / $one_col_device_less_481 . '%';
	?>

	.col1-layout .category-product.products-grid .item{
		width: <?php echo $one_class_device_less_481; ?>;
	}
	
	.col1-layout .category-product.products-grid .item:nth-child(<?php echo $one_col_device_less_481;?>n+1){
		clear:both;
	}

	/*==2 COLUMNS==*/
	<?php
	$two_col_device_less_481 = $_config->getProductListing('twocolumn_device_less_481');
	$two_class_device_less_481 = 100 / $two_col_device_less_481 . '%';
	?>

	.col2-layout .category-product.products-grid .item{
		width: <?php echo $two_class_device_less_481; ?>;
	}
	
	.col2-layout .category-product.products-grid .item:nth-child(<?php echo $two_col_device_less_481;?>n+1){
		clear:both;
	}

	/*==3 COLUMNS==*/
	<?php
	$three_col_device_less_481 = $_config->getProductListing('threecolumn_device_less_481');
	$three_class_device_less_481 = 100 / $three_col_device_less_481 . '%';
	?>

	.col3-layout .category-product.products-grid .item{
		width: <?php echo $three_class_device_less_481; ?>;
	}
	
	.col3-layout .category-product.products-grid .item:nth-child(<?php echo $three_col_device_less_481;?>n+1){
		clear:both;
	}
}

</style>
