<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>
<li class="item link compare">
   <div class="item link compare" data-bind="scope: 'compareProducts'" data-role="compare-products-link">
    <a class="action compare no-display my-compare" title="<?php /* @escapeNotVerified */ echo __('My Compare') ?>" href="<?php echo $block->getUrl('catalog/product_compare/index/')?>">
    <span class="text"><?php /* @escapeNotVerified */ echo __('My Compare') ?></span>
        <span class="counter qty" data-bind="text: compareProducts().countCaption"></span>
    </a>
</div>

</li>

<script type="text/x-magento-init">
{"[data-role=compare-products-link]": {"Magento_Ui/js/core/app": <?php /* @escapeNotVerified */ echo $block->getJsLayout();?>}}
</script> 