<?php
/*------------------------------------------------------------------------
 # VT Products - Version 1.0
 * Copyright (C) 2013 The VT Theme. All Rights Reserved.
 * @license - GNU/GPL, http://www.gnu.org/licenses/gpl.html
 * Author: VT Theme
 * Websites: http://www.vttheme.com
-------------------------------------------------------------------------*/
$categoryList = $this->getListCategoriesFilter();
//print_r($categoryList);
$_productCollection = $this->getLoadedProductCollection();
$_helper = $this->helper('catalog/output');
$uniqued = rand().time();

$imgWidth = $this->product_image_width;
$imgHeight = $this->product_image_height;
$orderby = $this->product_order_by;
$staticBlock = $this->stactic_block_name;
if ($imgWidth <= 0 || $imgHeight <= 0){
	$this->product_image_disp = false;
}

?>
<?php if(!$_productCollection->count()): ?>
	<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div id="box-cate-left" class="box-cate-left">
	<div class="box-info">
		<?php if($categoryList){ ?>			
		<div class="title t01">
			<?php echo $categoryList[0]->getName(); ?>
		</div>
		<?php }?>
		<div class="wrap-box-oderby">
			<div id="box-oderby" class="carousel slide" data-ride="carousel" data-interval="0">
				<div class="navslider">
					<a class="pv" href="#box-oderby" role="button" data-slide="prev">Previous</a>
					<a class="nt" href="#box-oderby" role="button" data-slide="next">Next</a>
				</div>
				<div id="orderby-product<?php echo $uniqued; ?>" class="carousel-inner">
					<div class="item active">
						<a class="ic01 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="best_sales" href="javascript:void(0);"><?php echo $this->__('Best sale'); ?></a>
						<div class="tmp"></div>
						<a class="ic02 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="most_viewed" href="javascript:void(0);"><?php echo $this->__('Most view'); ?></a>
					</div>
					<div class="item">
						<a class="ic03 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="top_rating" href="javascript:void(0);"><?php echo $this->__('Most reviews'); ?></a>
						<div class="tmp"></div>
						<a class="ic04 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="name" href="javascript:void(0);"><?php echo $this->__('Oderby name') ?></a>
					</div>
					<div class="item">
						<a class="ic05 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="created_at" href="javascript:void(0);"><?php echo $this->__('New arrivals') ?></a>
						<div class="tmp"></div>
						<a class="ic06 linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" data-orderby="random"  href="javascript:void(0);"><?php echo $this->__('Random'); ?></a>
					</div>
				</div>
			</div>
		</div>

		<?php
		if($categoryList){	?>
			<div id="list-category<?php echo $uniqued; ?>" class="list-category">
				<ul>
			<?php
			foreach ($categoryList as $key => $value)
			{
				if($key != 0){
				?>
				<li>
					<a class="linkItem" data-catid="<?php echo $value->getId(); ?>" href="javascript:void(0)<?php echo ""; //echo $value->getURL(); ?>">
						<?php echo $value->getName(); ?>
					</a>
				</li>
			<?php
				}
			}?>
				</ul>
			</div>
			<?php }
			?>
		<?php if($staticBlock){
			echo $this->getLayout()->createBlock('cms/block')->setBlockId($staticBlock)->toHtml();
		}?>
	</div>
	<div id="parent-category<?php echo $uniqued; ?>" class="box-image">
	<?php
		if($categoryList){?>
		<a class="linkItem" data-catid="<?php echo $categoryList[0]->getId(); ?>" href="javascript:void(0);">
			<img src="<?php echo $categoryList[0]->getImageUrl();?>" alt="<?php echo $categoryList[0]->getName(); ?>" />
		</a>	
	<?php	}
	?>
	</div>
</div>	
<div id="vt_slider<?php echo $uniqued; ?>" class="block vt-slider">	
	<div class="slider-inner">    	
	    <div class="container-slider">
		    <div class="products-grid">
		    <?php foreach($_productCollection as $_product) : ?>
		        <?php
		        $now = date("Y-m-d H:m:s");
		        $newsFrom= $_product->getNewsFromDate();
		        $newsTo=  $_product->getNewsToDate();
		        $specialprice = Mage::getModel('catalog/product')->load($_product->getId())->getSpecialPrice(); 
		        $special_from_date = $_product->getSpecialFromDate();
		        $special_to_date = $_product->getSpecialToDate();    
		        ?>
		        <div class="item">
		        	<?php   
		                if($newsFrom != ''){                            
		                if (($now>=$newsFrom && $now<=$newsTo)||($now>=$newsFrom && $newsTo =='')){  ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }else{
		                if(($newsTo != "") && $newsTo >= $now){ 
		                ?>
		                    <div class='new-item'><?php echo $this->__("new"); ?></div>
		                <?php }
		                }?>
		                <?php 
		                if (($specialprice && ($special_from_date <= $now) && ($special_to_date >= $now || $special_to_date =="" ))){?>
		                    <div class='sale-item'>
		                        <span class='first'><?php
		                        $saleof= abs(($specialprice/($_product->getPrice()))*100-100);?>
		                        <?php   print_r(floor($saleof)); ?>%</span><span><?php echo $this->__("off");?></span>
		                    </div>
		             <?php } ?>  
					<div class="item-wrap">
                    <div class="item-image">   
                        <a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>">
                        <img class="first_image" src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize($imgWidth,$imgHeight); ?>" alt="<?php echo $this->stripTags($this->getImageLabel($_product, 'small_image'), null, true) ?>" /> 
                        </a>
                        <div class="item-btn">
                        	<div class="box-inner">
                            <?php if ($this->helper('wishlist')->isAllow()) : ?>
                               <a title="<?php echo $this->__('Add to wishlist') ?>" href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>" class="link-wishlist"><?php //echo $this->__('Add to Wishlist') ?></a>
                            <?php endif; ?>                            
                           <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?>
                            <a title="<?php echo $this->__('Add to compare') ?>" href="<?php echo $_compareUrl ?>" class="link-compare"><?php //echo $this->__('Add to Compare') ?></a>
                            <?php endif; ?>
                        	</div>                            
                        </div>  
                        <?php if($_product->isSaleable()): ?>
                            <a title="<?php echo $this->__('Add to cart') ?>" class="btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><?php echo $this->__('Add to Cart') ?></a>
                        <?php else: ?>
                            <a href="#" class="availability out-of-stock"><?php echo $this->__('Out of stock') ?></a>
                        <?php endif; ?>
                    </div>   
                       
                    <div class="pro-info">
                        <div class="pro-inner">
                           <div class="pro-title product-name"><a href="<?php echo $_product->getProductUrl() ?>"><?php echo $this->escapeHtml($_product->getName()) ?></a></div>    
                           <div class="pro-content">    
                                <div class="wrap-price"> 
                                <?php echo $this->getPriceHtml($_product, true) ?> 
                                </div>
                                 <?php echo $this->getReviewsSummaryHtml($_product,'short',true) ?>
                           </div>
                        </div>                                                                        
                    </div>
                    
                </div><!--end item wrap -->
		        </div>
		    <?php endforeach; ?>
		    </div>
		</div>
		<div class="navslider">
			<a class="prev" href="#">Prev</a>
			<a class="next" href="#">Next</a>
		</div>
	</div>
</div>
<script type="text/javascript">
//<![CDATA[	
    var flycart_associated_products = <?php echo $this->getFlycartAssociatedProduct(); ?>;         
//]]>
</script>
<script type="text/javascript">
//<![CDATA[
    jQuery(document).ready(function($) {
        function productSlider(){
	        $('#vt_slider<?php echo $uniqued; ?> div.products-grid').owlCarousel({
	        	items: 4,
	            itemsCustom: [ 
	            	[0, <?php echo $this->screen_phone; ?>], 
	            	[480, <?php echo $this->screen_xs; ?>], 
	            	[768, <?php echo $this->screen_sm; ?>], 
	            	[992, <?php echo $this->screen_md; ?>], 
	            	[1200, <?php echo $this->screen_lg; ?>] 
	            ],
	            pagination: false,
	            slideSpeed : 800,
	            addClassActive: true,
	            scrollPerPage: false,
				afterAction: function (e) {
				    if(this.$owlItems.length > this.options.items){
				        $('#vt_slider<?php echo $uniqued; ?> .navslider').show();
				    }else{
				        $('#vt_slider<?php echo $uniqued; ?> .navslider').hide();
				    }
				}
	            //scrollPerPage: true,
	        });
			$('#vt_slider<?php echo $uniqued; ?> .navslider .prev').on('click', function(e){
				e.preventDefault();
				$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.prev');
			});
			$('#vt_slider<?php echo $uniqued; ?> .navslider .next').on('click', function(e){
				e.preventDefault();
				$('#vt_slider<?php echo $uniqued; ?> div.products-grid').trigger('owl.next');
			});
		}
		
		productSlider();
		(function(element){
			var $element = $(element);
			
			cateInfo = $('.linkItem',$element);
			ajax_url="<?php echo Mage::getBaseUrl().'productsconfig/index/ajax' ?>";
			
			cateInfo.click(function(){
				$('#list-category<?php echo $uniqued; ?> li a').each(function(){
					$(this).removeClass('actived');
				})
				$(this).addClass('actived');
				$('#vt_slider<?php echo $uniqued; ?>').addClass('loading');
				catid = $(this).attr('data-catid');
				var item = $('.linkItem','#orderby-product<?php echo $uniqued; ?>');
				item.each(function(){
					$(this).attr('data-catid',catid);					
				});
				orderby = $(this).attr('data-orderby');
				if(orderby==''){
					orderby="name";
				}
				$.ajax({
						type: 'POST',
						url: ajax_url,
						data:{							
							catid: catid,
							orderby: orderby,						
						},
						success: function(result){
							$('#vt_slider<?php echo $uniqued; ?> .slider-inner').remove();
							$('#vt_slider<?php echo $uniqued; ?>').html(result.listProducts);	
							productSlider();
							$('#vt_slider<?php echo $uniqued; ?>').removeClass('loading');
						},
						dataType:'json'
					});
			});
			
		})('#list-category<?php echo $uniqued; ?>,#parent-category<?php echo $uniqued; ?>,#orderby-product<?php echo $uniqued; ?>');
    });
//]]>
</script>
<?php endif; ?>